# CK3 고유명사 사전
# 이름, 가문명, 지명 등의 고유명사

"abbad" = "아바드"
"abbatissa" = "아바티사"
"abbaye" = "아바예"
"abohyen" = "아보히엔"
"abs" = "압스"
"abso" = "압소"
"actwin" = "악트윈"
"aðalsmær" = "아달스매르"
"adiutor" = "아디우토르"
"adorad" = "아도라드"
"ængli" = "앵글리"
"ærnbiorn" = "에른비요른"
"af fasge" = "아프 파스게"
"af möre" = "아프 뫼레"
"altocumulus" = "알토큐물러스"
"alusian" = "알루시안"
"anger" = "안거"
"anuket" = "아누케트"
"apt" = "압트"
"arghun-agha" = "아르군-아그하"
"árpádné" = "아르파데"
"astride" = "아스트라이드"
"augur" = "아우구르"
"auspex" = "우아수펙스"
"auxilia" = "아우실리아"
"bailjar" = "벨자르"
"balgarsko" = "발가르스코"
"bandita" = "반디타"
"barber" = "바버"
"barde" = "바데"
"baue" = "바우에"
"beg" = "베그"
"benvenuto" = "벤베누토"
"bertalan" = "베르탈란"
"bet" = "베트"
"bienfaite" = "비엔페이트"
"biornolf" = "비오르놀프"
"blackbird" = "블랙버드"
"blemmyae" = "블렘미"
"blemmye" = "블렘미"
"blemmyes" = "블렘미"
"bogyoszló" = "보교슬로"
"bolanudik" = "볼라누딕"
"botta-adorno" = "보타-아도르노"
"bouchardides" = "부샤르디데스"
"boudewijn" = "바우더베인"
"bozok" = "보조크"
"břetislav" = "브르제티슬라프"
"bugge" = "부게"
"butler" = "버틀러"
"butsuntorn" = "부츠순톤"
"capellan" = "카펠란"
"capito" = "카피토"
"carpenter" = "카펜터"
"castelman" = "카스텔만"
"cavalca" = "카발카"
"chios" = "히오스"
"chongjin" = "총진"
"chongzhe" = "총저"
"chug" = "처그"
"civilis" = "시빌라스"
"clericus" = "클레리쿠스"
"cockburn" = "코번"
"coel" = "코일"
"commercy" = "코메르시"
"comnenus" = "콤니누스"
"comps" = "콤프스"
"congcan" = "총찬"
"conghou" = "총후"
"congjing" = "총징"
"congke" = "총커"
"congmin" = "총민"
"congrong" = "총룽"
"congshen" = "총선"
"congwen" = "총원"
"connistant" = "코니스탄트"
"conratsch" = "콘라트"
"conratz" = "콘라츠"
"constantinian" = "콘스탄티니안"
"contessa" = "콘테사"
"contesson" = "콘테송"
"cop" = "코프"
"cormac cas" = "코맥 카스"
"coronel" = "코로넬"
"corp" = "코르프"
"corradino" = "콘라디노"
"corwn" = "코르운"
"cozzi" = "코지"
"creada" = "크레아다"
"creat" = "창크레아트"
"crysoing" = "크라이소잉"
"csalán" = "찰란"
"császár" = "차사르"
"cunzhang" = "춘장"
"cunzhen" = "춘전"
"cunzhi" = "춘지"
"cusenza" = "콘젠차"
"cust" = "쿠스트"
"custancia" = "콘스탄시아"
"dammartin" = "다마르틴"
"dandy" = "댄디"
"danske" = "단스케"
"darie" = "다리에"
"dativus" = "다티부스"
"daugaard" = "다우고르"
"defendens" = "테펜덴스"
"deogratias" = "데오그라티아스"
"deòras" = "데오라스"
"depre" = "데프레"
"designatus" = "디사그나투스"
"detern" = "데테른"
"detvanský" = "데트반스키"
"dharma" = "다르마"
"dharmaraja manabhita" = "다르마라자 마나브히타"
"dharmatrate" = "다르마트라테"
"diexi" = "디에시"
"dinastia" = "디나스티아"
"dir" = "디르"
"dire" = "디레"
"disette" = "디셋트"
"distrude" = "디스트루드"
"dobýta" = "도비타"
"doch" = "도치"
"doe" = "두"
"doede" = "두데"
"doeke" = "두케"
"doll" = "돌"
"dolors" = "돌로스"
"doman" = "도만"
"dömien" = "도미엔"
"dominator" = "도미나토르"
"doranites" = "도라니테스"
"dost" = "도스트"
"dowse" = "다우스"
"drotning" = "드로트닝"
"drottningmóðir" = "드로트닝모디르"
"duce" = "두체"
"ducovsky" = "두코프스키"
"ducovský" = "듀코브스키"
"dud" = "두드"
"dugu" = "두구"
"dujma" = "두이마"
"duk" = "두크"
"dukedal" = "두크달"
"duko" = "두코"
"duktsuk" = "둑트석"
"dukum" = "두쿰"
"dulce" = "둘세"
"eagar" = "에거"
"effemy" = "에페미"
"eilivus" = "에일리부스"
"elephantine" = "엘레판티네"
"emai" = "에마이"
"emble" = "엠브레"
"emblem" = "엠블렘"
"enged" = "엔게드"
"engerand" = "엥게란드"
"englesia" = "잉글레시아"
"engolf" = "엔골프"
"erdzivil" = "에르드지빌"
"este" = "에스테"
"evangelicus" = "에반겔리쿠스"
"ewsum" = "에우숨"
"eymer" = "에이머"
"fader" = "파더"
"faste" = "파스테"
"fastrun" = "파스트런"
"fatherling" = "파덜링"
"fathrr" = "파트르"
"fauconnier" = "포코니에"
"fella" = "펠라"
"fellow" = "펠로우"
"feodukta" = "페오둑타"
"fermentin" = "페르멘틴"
"fin" = "핀"
"fllipin" = "플리핀"
"florence" = "플로렌스"
"flotte" = "플로테"
"frænde" = "프뢴데"
"frændr" = "프랜드르"
"frände" = "프롼데"
"franki" = "프랑키"
"franku" = "프랑쿠"
"franqueite" = "프랑케트"
"freond" = "프레온드"
"frethold" = "프레톨드"
"frienday" = "프리엔데이"
"fylki" = "퓔키"
"gails" = "가일스"
"gallego" = "가예고"
"ganga" = "스베타카 강가"
"ganger" = "갱어"
"garners" = "가너스"
"gautans" = "가우탄스"
"gedongwani" = "게동와니"
"gekun" = "게쿤"
"gentile" = "겐틸레"
"gentilis" = "젠틸리스"
"gentoo" = "젠투"
"giblet" = "지블레"
"gisalēiks" = "기살릭스"
"gjörð" = "괴르드"
"gjörva" = "괴르바"
"gladius christi" = "글라디우스 크리스티"
"głogowski" = "그워고프스키"
"glymes" = "글림스"
"gnyal" = "냘"
"godchilde" = "고드칠드"
"godday" = "고데이"
"gode" = "고디"
"godlamb" = "고드램"
"godlid" = "고드리드"
"godman" = "고드맨"
"godson" = "고드손"
"godsven" = "고스벤"
"gök" = "괴크"
"gökhan" = "괴크한"
"goodfellow" = "구드펠로우"
"gorgonia" = "고르고니아"
"gøye" = "괴에"
"gramr" = "그람"
"grand" = "그랜드"
"grandson" = "그랜슨"
"grannd" = "그랜드"
"grant" = "그랜트"
"green" = "그린"
"gregoir" = "그레구아르"
"grey" = "그레이"
"grimberghe" = "흐림베르허"
"grimmingen" = "흐리밍겐"
"grip" = "그리프"
"gróða" = "그로다"
"grootheid" = "흐로트헤이트"
"gross" = "그로쓰"
"gruffydd" = "그리피드"
"gruningen" = "그루닝겐"
"grzymała" = "그지미와"
"gualandi" = "괄란디"
"gualch" = "괄크"
"guard" = "가드"
"güçlü" = "귀츨뤼"
"gudelig" = "구델링"
"guideschi" = "구이데스키"
"guise" = "기즈"
"gundsulfs" = "군둘프스"
"gute" = "구테"
"gutkeled" = "구트켈레드"
"gyðingr" = "귀딩그르"
"hachberg" = "하흐베르크"
"hack" = "핵"
"hárdrottningmóðir" = "하르드로트닝모디르"
"hárlingja" = "하를링갸"
"hästesko" = "헤스테스코"
"heiðingi" = "헤이딩기"
"helpman" = "헬프맨"
"helviz" = "헬비즈"
"heralde" = "헤랄데"
"heroi" = "헤로이"
"herold" = "헤롤드"
"hertug" = "헤르투그"
"hew" = "헤우"
"hexi" = "하서"
"hezhenbao" = "허저보"
"hick" = "힉"
"hirðjarl" = "히르드야를"
"hirðjarldómr" = "히르드야를돔르"
"hirðjarldóttir" = "히르드야를도티르"
"hirðjarlfru" = "히르드야를프루"
"hirðjarlmóðir" = "히르드야를모디르"
"histro" = "히스트로"
"hiya" = "히야"
"hkwi" = "흑위"
"hmu" = "흐무"
"hobby" = "하비"
"höfðingi" = "회프딩기"
"höfðingifru" = "회프딩기프루"
"höfðingsmóðir" = "회프딩스모디르"
"honnorée" = "호노리"
"horus" = "호루스"
"howsa" = "하우사"
"hrabec" = "흐라벡"
"huffin" = "휴핀"
"hunisco" = "후니스코"
"hunno" = "후노"
"husewyf" = "후스위프"
"hyvälempi" = "휘배램피"
"hyväneuvo" = "휘배네우보"
"hyvätty" = "휘베티"
"ikä" = "이캐"
"ikämieli" = "이캐미엘리"
"ikäneuvo" = "이캐네우보"
"i̇lçen" = "일켄"
"imhotep" = "임호테프"
"ingulf" = "잉굴프"
"inhalt" = "인할트"
"ire" = "아이레"
"isfahání" = "이스파한니"
"isis" = "이시스"
"isle" = "아일"
"italienzug" = "이탈리엔추크"
"ive" = "이브"
"jacket" = "자케트"
"jackett" = "자케트"
"jacomyn" = "자코민"
"jannetin" = "잔네탱"
"janniting" = "잔니팅"
"jaquema" = "자케마"
"jarldómr" = "야를돔르"
"jarlfru" = "야를프루"
"jarlmóðir" = "야를모디르"
"jarlsfrende" = "야를프렌데"
"jehane" = "잔"
"jehanne" = "잔느"
"jehannette" = "자네트"
"jehosua" = "조슈아"
"joachimie" = "요아키미"
"jogchum" = "요그훔"
"jordans" = "요르단"
"josepa" = "주세파"
"joye" = "조에"
"junyi" = "준이"
"jurate" = "유라테"
"jurchedei" = "주르체데이"
"juries" = "유리스"
"jute" = "유테"
"kadamba" = "카담바"
"kalabsha" = "칼라브샤"
"karakoram" = "카라코람"
"kaukoheimo" = "카우코헤이모"
"kaysite" = "카이사이트"
"kemiläinen" = "케미라이넨"
"khalajes" = "칼라제스"
"khamite" = "하미테"
"khapipe" = "하피페"
"khattime" = "카티메"
"khnum" = "크눔"
"kid" = "키드"
"komnene" = "콤니니"
"komnenid" = "콤니노스"
"komnenodoukas" = "콤니노두카스"
"komnenos" = "콤니노스"
"komnenos axuchos" = "콤니노스 악수호스"
"komnenos doukas" = "콤니노스 두카스"
"konradiner" = "콘라디너"
"konungsbróðir" = "콩스브로르"
"kujawski" = "쿠야비스키"
"kuningas" = "쿠닝가스"
"kuuluva" = "쿨루바"
"kyllä" = "퀼래"
"labourd" = "라부르"
"ladakhi" = "라다키"
"lambkin" = "램킨"
"lander" = "랜더"
"landeven" = "란데벤"
"lang" = "랑그"
"langsom" = "랭섬"
"larron" = "라롱"
"lava" = "라바"
"law" = "로우"
"lector" = "렉토르"
"leg" = "레그"
"lendirmeý" = "렌디르메위"
"leonés" = "레오네스"
"leshang" = "러샹"
"líf" = "리프"
"lodolfidi" = "로돌피디"
"loloho" = "로로호"
"löve" = "뢰베"
"lovechild" = "러브차일드"
"lowe" = "로위"
"maghons" = "마곤스"
"mágsefni" = "마그세프니"
"malmury" = "맬무어리"
"mamma" = "맘마"
"man" = "만"
"mánagarmr" = "마나가름"
"mandulis" = "만둘리스"
"maons" = "마온스"
"march" = "마르치"
"marchesa" = "마르체사"
"margrave" = "마그레브"
"marine" = "마린"
"marquert" = "마르쿼트"
"marquesa" = "마르퀘사"
"marquise" = "마르키스"
"mastic" = "유향"
"maudlin" = "모들린"
"mauric" = "마우리티우스"
"megas komnenos" = "메가스 콤니노스"
"memorantia" = "메모란티아"
"meu" = "메으"
"meurakas" = "메우라카스"
"mielenpito" = "미엘렌피토"
"mieli" = "미엘리"
"mielivalta" = "미엘리발타"
"mild" = "마일드"
"militije" = "밀리시예"
"móðir" = "모디르"
"monachus" = "모나쿠스"
"moth" = "모스"
"mother" = "마더"
"mousson" = "무송"
"moustakes" = "무스타케스"
"müjde" = "뮈즈데"
"mujoklung" = "무조클룽"
"muksam" = "묵삼"
"mule" = "뮬"
"mustacon" = "무스타콘"
"mutinid" = "무티니드"
"namdol" = "남돌"
"nepokoj" = "네포코이"
"nikephorian" = "니케포리안"
"nikerites" = "니케라이트"
"nkurange" = "응쿠란게"
"norge" = "노르게"
"notarius" = "노타리우스"
"novak" = "노바크"
"nowak" = "노바크"
"obožen" = "오보젠"
"ode" = "오드"
"öge" = "외귀"
"øgot" = "외고트"
"okrun" = "오크룬"
"opportune" = "오포르투네"
"oristani" = "오리스타니"
"orkneyjar" = "오크네야르"
"orphanotrophos" = "오르파노트로포스"
"osiris" = "오시리스"
"ottonian" = "오토니안"
"ouyang" = "오양"
"padres" = "파드레스"
"pagan" = "파간"
"pagano" = "파가노"
"paganus" = "파가누스"
"papie" = "파피에"
"participazio" = "파르티치파치오"
"pay de provence" = "페이 드 프로방스"
"paynot" = "페이노트"
"peacock" = "피콕"
"peganites" = "페가니테스"
"pegonites" = "페고니테스"
"pełczybog" = "펠치복"
"pentecoste" = "펜테코스테"
"penticost" = "펜티코스트"
"philae" = "필레"
"piratamâtevi" = "피라타마테비"
"poduoluo" = "포두오뤄"
"pohansky" = "포한스키"
"pohanský" = "포한스키"
"ponislava" = "포니슬라바"
"ponzone" = "폰조네"
"porta argentea" = "포르타 아르겐티아"
"posthuma" = "포스쑤마"
"potens" = "포텐스"
"poubelle" = "푸벨"
"prosdokimos" = "프로스도키모스"
"puke" = "푸케"
"qdlingja" = "오들링갸"
"qdlingr" = "오들링그르"
"qingdou" = "칭더우"
"rdeciv" = "르데치프"
"reinald" = "레이날드"
"revel" = "르벨"
"ribellés" = "리벨레스"
"ríki" = "리키"
"ringware" = "링웨어"
"rma" = "르마"
"robertine" = "로베르틴"
"romorantin" = "로모란틴"
"roseola" = "로셀라"
"roul" = "로울"
"sæbeorn" = "세베른"
"saenjaibarn" = "샌자이반"
"saint_sépulcre" = "생세퓔크르"
"saint-clair" = "생 클레르"
"saint-denis" = "생 드니"
"saint-gilles" = "생 질"
"saint-menehould" = "생 메눌"
"saint-paul" = "생 폴"
"saint-pol" = "생 폴"
"saint-sauveur" = "생 소뵈르"
"saint-severin" = "생 세브랭"
"saint-valery" = "생 발레리"
"saint-valéry" = "생 발레리"
"saintisme" = "생티즘"
"sales" = "살레스"
"salian" = "잘리어"
"salvaing" = "살바잉"
"salvia" = "살비아"
"sancta" = "상크타"
"sane" = "사네"
"saracena" = "사라체나"
"satet" = "사티스"
"satis" = "사티스"
"satjit" = "사티스"
"savage" = "세비지"
"say" = "세이"
"schelden" = "스헬던"
"schleswig-holstein-sonderburg-glücksburg" = "슐레스비히홀슈타인존더부르크글뤼크스부르크"
"sciencia" = "시엔티아"
"seafowl" = "시파울"
"sedile" = "세딜레"
"self" = "셀프"
"señora" = "세뇨라"
"sense" = "센스"
"shiping" = "시핑"
"sichilde" = "지힐데"
"sicur" = "시쿠르"
"siegeval" = "시제발"
"siegevaut" = "시제보"
"signor" = "시그노르"
"sinhala" = "싱할라어"
"skalp" = "스칼프"
"slavac" = "슬라박"
"slavich" = "슬라비치"
"smádrottningmóðir" = "스마드로트닝모디르"
"smákonungr" = "스마코눙그르"
"smákonungsdrottning" = "스마코눙그스드로트닝"
"smálingja" = "스말링갸"
"smith" = "스미스"
"sobieslaw" = "소비에슬로우"
"soop" = "수프"
"sorbi" = "소르브"
"sortes" = "소르테스"
"soules" = "술"
"spa" = "스파"
"splinter" = "스플린터"
"stad" = "스타드"
"staert" = "스타르트"
"stake" = "스테크"
"steuen" = "스테번"
"stewart" = "스튜어트"
"steynaert" = "스테이나르트"
"stóldrottning" = "스톨드로트닝"
"stóldrottningmóðir" = "스톨드로트닝모디르"
"stólingja" = "스톨링갸"
"stóljarlmær" = "스톨야를메르"
"stólkonungr" = "스톨코눙그르"
"storm" = "스토름"
"suevisco" = "수비스코"
"sufficia" = "슈피시아"
"sun" = "선"
"supplicia" = "수플리카"
"svärd" = "스바르드"
"sweetlove" = "스위트로브"
"sydänmaa" = "시댄마"
"syriam" = "시리암"
"szalók" = "살로크"
"szegény" = "세체니"
"szentgyörgyi" = "선트죄르지"
"szerencsés" = "세렌세스"
"szilágyi" = "실라지"
"tarkhanid" = "타르카니드"
"taszi" = "타시"
"tásziszló" = "타실로"
"tebrik" = "테브리크"
"tematínský" = "테마틴스키"
"teoufraste" = "테오프라스트"
"termes" = "테르메스"
"tèrmini" = "테르미니"
"theoric" = "테오릭"
"thes" = "테스"
"thrugot" = "트루곳"
"thubten" = "툽텐"
"thurcytel" = "서케텔"
"thys" = "티스"
"tian" = "톈"
"tiande" = "천덕"
"tiers" = "티에르스"
"timostrate" = "티모스트라테"
"tingzhi" = "팅즈"
"tõeleid" = "톨레이드"
"töhötöm" = "터허텀"
"tóim snáma" = "톰 스나마"
"tokzsiangx" = "톡상"
"toll" = "톨"
"tonger" = "통거"
"tórian" = "토리안"
"tribuno" = "트리부노"
"tries" = "트리스"
"triungngienh" = "쯔엉응우옌"
"trongsa" = "트롱사"
"truk" = "쭉"
"tsaatan" = "차탄"
"tsepong" = "체퐁"
"tsongkha" = "총카"
"turgish" = "투르키쉬"
"turken" = "투르켄"
"tutu" = "투투"
"udder" = "우더"
"ukjent" = "우셴트"
"undirdrottning" = "운디르드로트닝"
"undirdrottningmóðir" = "운디르드로트닝모디르"
"undirkonungr" = "운디르코눙그르"
"undirlingja" = "운디를링갸"
"undirlingr" = "운디를링그르"
"une" = "우네"
"unre" = "운레"
"unret" = "운레트"
"útlagi" = "우틀라기"
"vandaspagan" = "반다스파간"
"verteig" = "페르타이크"
"víðkunnr" = "비드쿤르"
"violent" = "비올렌트"
"vital" = "비탈"
"vrederick" = "브레데릭"
"vrolijk" = "브롤릭"
"vuppadeva" = "부파데바"
"wakhan" = "와한"
"wandalar" = "완달라"
"wander" = "완다"
"wandregisel" = "완드레기셀"
"water" = "월터"
"we" = "베"
"wechtaridi" = "베흐타링기"
"wegelenzi" = "베겔렌치"
"wei" = "웨이"
"wenmo" = "올말"
"wihomarc" = "위호마르크"
"wilco" = "빌코"
"withi" = "위디"
"wrage" = "라게"
"wreth" = "레스"
"wrister" = "브리스터"
"writser" = "브리처"
"yatim" = "야팀"
"yfame" = "이팜"
"yfirdrottning" = "위피르드로트닝"
"yfirdrottningmóðir" = "위피르드로트닝모디르"
"yfirkonungr" = "위피르코눙그르"
"yfirlingja" = "위피를링갸"
"yfirlingr" = "위피를링그르"
"yfirríki" = "위피르리키"
"ylian" = "일리안"
"yoih" = "요이"
"yoix" = "요익"
"you" = "요우"
"ysabeau" = "이사보"
"yüceay" = "위제"
"yüceun" = "위첸"
"yughur" = "위구르"
"zarin-kemer" = "자린-케메르"
"zhebu" = "절포"
"ziek" = "지엑"
"ziemzjenx" = "짐선"
"zjex" = "젝"
"zunwang" = "준왕"
"þióðbjǫrg" = "시오드비요르그"
"þiúðborg" = "슈드보르그"
"þjóðdrottning" = "쇼드드로트닝"
"þjóðdróttningmóðir" = "쇼드드로트닝모디르"
"þjóðgerðr" = "쇼드게르드"
"þjóðheiðr" = "쇼드헤이드"
"þjóðhildr" = "쇼드힐드르"
"þjóðkonungr" = "쇼드코눙그르"
"þjóðlingja" = "쇼들링갸"
"þjóðlingr" = "쇼들링그르"
"þjóðríki" = "쇼드리키"
"þjóðvé" = "쇼드베"
"þjófi" = "쇼피"
"þvari" = "트바리"

# 가문명 접두사 (공백으로 끝남)
"a " = "아 "
"af " = "아프 "
"an " = "안 "
"ap " = "아프 "
"av " = "아브 "
"banu " = "바누 "
"d'" = "디 "
"da " = "다 "
"dai " = "다이 "
"dal " = "달 "
"dalle " = "달리 "
"de " = "데 "
"de la " = "드 라 "
"de las " = "드 라스 "
"de les " = "드 레스 "
"de los " = "데 로스 "
"degli " = "데글리 "
"dei " = "데이 "
"del " = "델 "
"della " = "델라 "
"des " = "데스 "
"di " = "디 "
"din " = "딘 "
"do " = "하라 "
"du " = "두 "
"ferch " = "페르흐 "
"filius " = "필리우스 "
"fitz" = "피츠 "
"gada " = "가다 "
"guy " = "기 "
"i " = "나 "
"iš " = "이쉬 "
"kohta " = "코타 "
"la " = "라 "
"le " = "레 "
"m " = "엠 "
"mac " = "맥 "
"map " = "맵 "
"mem " = "멤 "
"merch " = "메르흐 "
"mn " = "엠엔 "
"mwa " = "므와 "
"na " = "나 "
"nava " = "나바 "
"O' " = "오 "
"od " = "오디 "
"of " = "오브 "
"ondol" = "온돌"
"ot " = "오티 "
"tkacer " = "트카체르 "
"ton " = "톤 "
"ua " = "우아 "
"ui " = "우이 "
"ult " = "울트 "
"van " = "반 "
"van der " = "반 데르 "
"vch " = "베흐 "
"ve " = "베 "
"von " = "폰 "
"z " = "즈 "
"ze " = "제 "
"zu " = "주 "
